spring.application.name=nextfeet
spring.datasource.url=jdbc:h2:mem:nextfeet;MODE=MySQL;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.sql.init.mode=always
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp
spring.mvc.hiddenmethod.filter.enabled=true
spring.h2.console.enabled=true
server.port=8080
