DROP TABLE IF EXISTS oferta_producto;
DROP TABLE IF EXISTS oferta_categoria;
DROP TABLE IF EXISTS oferta;
DROP TABLE IF EXISTS detalle_pedido;
DROP TABLE IF EXISTS pedido;
DROP TABLE IF EXISTS carrito_item;
DROP TABLE IF EXISTS carrito;
DROP TABLE IF EXISTS direccion;
DROP TABLE IF EXISTS stock_talla;
DROP TABLE IF EXISTS zapatilla;
DROP TABLE IF EXISTS categoria;
DROP TABLE IF EXISTS usuario;
CREATE TABLE usuario (id INT AUTO_INCREMENT PRIMARY KEY, nombres VARCHAR(100) NOT NULL, apellidos VARCHAR(100), correo VARCHAR(160) UNIQUE NOT NULL, password VARCHAR(255) NOT NULL, telefono VARCHAR(30), rol VARCHAR(20) NOT NULL, estado VARCHAR(20) NOT NULL DEFAULT 'ACTIVO');
CREATE TABLE categoria (id INT AUTO_INCREMENT PRIMARY KEY, nombre VARCHAR(100) UNIQUE NOT NULL, descripcion VARCHAR(500), estado VARCHAR(20) DEFAULT 'ACTIVO');
CREATE TABLE zapatilla (id INT AUTO_INCREMENT PRIMARY KEY, sku VARCHAR(50) UNIQUE NOT NULL, nombre VARCHAR(150) NOT NULL, marca VARCHAR(100), precio DECIMAL(10,2) NOT NULL, descripcion VARCHAR(1000), materiales VARCHAR(500), colores VARCHAR(300), imagen VARCHAR(500), categoria_id INT, estado VARCHAR(20) DEFAULT 'ACTIVO', FOREIGN KEY(categoria_id) REFERENCES categoria(id));
CREATE TABLE stock_talla (id INT AUTO_INCREMENT PRIMARY KEY, zapatilla_id INT NOT NULL, talla VARCHAR(10) NOT NULL, cantidad INT NOT NULL DEFAULT 0, UNIQUE(zapatilla_id,talla), FOREIGN KEY(zapatilla_id) REFERENCES zapatilla(id));
CREATE TABLE direccion (id INT AUTO_INCREMENT PRIMARY KEY, usuario_id INT NOT NULL, ciudad VARCHAR(100), distrito VARCHAR(100), direccion_exacta VARCHAR(250), referencias VARCHAR(500), FOREIGN KEY(usuario_id) REFERENCES usuario(id));
CREATE TABLE carrito (id INT AUTO_INCREMENT PRIMARY KEY, usuario_id INT UNIQUE NOT NULL, FOREIGN KEY(usuario_id) REFERENCES usuario(id));
CREATE TABLE carrito_item (id INT AUTO_INCREMENT PRIMARY KEY, carrito_id INT NOT NULL, zapatilla_id INT NOT NULL, talla VARCHAR(10) NOT NULL, cantidad INT NOT NULL, UNIQUE(carrito_id,zapatilla_id,talla), FOREIGN KEY(carrito_id) REFERENCES carrito(id), FOREIGN KEY(zapatilla_id) REFERENCES zapatilla(id));
CREATE TABLE pedido (id INT AUTO_INCREMENT PRIMARY KEY, codigo VARCHAR(50) UNIQUE NOT NULL, usuario_id INT NOT NULL, direccion_id INT, fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP, total DECIMAL(10,2) NOT NULL, estado VARCHAR(30) NOT NULL, metodo_pago VARCHAR(30), motivo_anulacion VARCHAR(500), FOREIGN KEY(usuario_id) REFERENCES usuario(id), FOREIGN KEY(direccion_id) REFERENCES direccion(id));
CREATE TABLE detalle_pedido (id INT AUTO_INCREMENT PRIMARY KEY, pedido_id INT NOT NULL, zapatilla_id INT NOT NULL, talla VARCHAR(10), cantidad INT, precio_unitario DECIMAL(10,2), subtotal DECIMAL(10,2), FOREIGN KEY(pedido_id) REFERENCES pedido(id), FOREIGN KEY(zapatilla_id) REFERENCES zapatilla(id));
CREATE TABLE oferta (id INT AUTO_INCREMENT PRIMARY KEY, nombre VARCHAR(150), tipo VARCHAR(20) NOT NULL, valor DECIMAL(10,2) NOT NULL, fecha_inicio DATE, fecha_fin DATE, estado VARCHAR(20) DEFAULT 'ACTIVO');
CREATE TABLE oferta_producto (oferta_id INT, zapatilla_id INT, PRIMARY KEY(oferta_id,zapatilla_id), FOREIGN KEY(oferta_id) REFERENCES oferta(id), FOREIGN KEY(zapatilla_id) REFERENCES zapatilla(id));
CREATE TABLE oferta_categoria (oferta_id INT, categoria_id INT, PRIMARY KEY(oferta_id,categoria_id), FOREIGN KEY(oferta_id) REFERENCES oferta(id), FOREIGN KEY(categoria_id) REFERENCES categoria(id));
